chage test

diff --git a/.github/ci.yml b/.github/ci.yml
--- a/.github/ci.yml
+++ b/.github/ci.yml
@@ -9,6 +9,7 @@ jobs:
       - name: checkout code
         uses: actions/checkout@v4
       - name: Build image
+        run: docker build -t ${{ secrets.DOCKER_TEST}}/cuportfolio${{github.run_number}}
         run: docker build -t ${{ secrets.DOCKER_TEST}}/cuportfolio .
       - name: Docker login
         uses: docker/login-action@v4
@@ -17,8 +18,21 @@ jobs:
           password: ${{ secrets.DOCKER_PASSWORD }}
 
       - name: Push image to registry
-        run: docker push ${{ secrets.DOCKER_TEST}}/cuportfolio .
-      
-     
+        run: 
+          docker push ${{ secrets.DOCKER_TEST}}/ciportfolio${{github.run_number}}
+          docker push ${{ secrets.DOCKER_TEST}}/ciportfolio .
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: SSh to Linux and run a container
+        uses: appleboy/ssh-action@v1
+  with:
+    host: ${{ secrets.HOST }}
+    username: ${{ secrets.SSH_USERNAME }}
+    key: ${{ secrets.PRIVATE_KEY }}
+    script: 
+        docker rm -f portfolio || echo "Container not found, skipping removal"
+        docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_TEST}}/ciportfolio .
       
       
